# Import required libraries
import pandas as pd  # For data manipulation
import numpy as np  # For numerical operations
import os  # For file operations
from datetime import datetime  # For timestamps

# Print header
print("=" * 80)
print("STAGE 6: FEATURE ENGINEERING & METRICS LAYER")
print("=" * 80)
print()

# Define file paths
input_path = "data/processed/clean_churn_data.csv"
output_path = "data/processed/enriched_churn_data.csv"
dictionary_path = "data/processed/feature_dictionary.txt"
validation_path = "data/processed/feature_validation_report.txt"

# Check if input file exists
if not os.path.exists(input_path):
    print(f"❌ ERROR: Clean dataset not found at {input_path}")
    print(f"   Please run Stage 4 (data_cleaning.py) first")
    exit()

# Load the clean dataset
print("📂 Loading clean dataset...")
df = pd.read_csv(input_path)
print(f"✅ Dataset loaded: {input_path}")
print(f"   Original shape: {df.shape[0]} rows × {df.shape[1]} columns")
print()

# Initialize lists for documentation
feature_dict = []  # Feature dictionary entries
validation_results = []  # Validation results

# Add headers to documentation
feature_dict.append("=" * 80)
feature_dict.append("FEATURE DICTIONARY")
feature_dict.append("=" * 80)
feature_dict.append("")
feature_dict.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
feature_dict.append(f"Source Dataset: {input_path}")
feature_dict.append("")

validation_results.append("=" * 80)
validation_results.append("FEATURE VALIDATION REPORT")
validation_results.append("=" * 80)
validation_results.append("")
validation_results.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
validation_results.append("")

# ==================== CATEGORY 1: CUSTOMER VALUE METRICS ====================
print("-" * 80)
print("CATEGORY 1: CUSTOMER VALUE METRICS")
print("-" * 80)

feature_dict.append("-" * 80)
feature_dict.append("CATEGORY 1: CUSTOMER VALUE METRICS")
feature_dict.append("-" * 80)

validation_results.append("-" * 80)
validation_results.append("CATEGORY 1: CUSTOMER VALUE METRICS")
validation_results.append("-" * 80)

# Feature 1: Customer Lifetime Value (CLV)
# Business Definition: Total revenue generated by customer during their lifetime
# Calculation: TotalCharges (cumulative revenue to date)
print("\n📊 Creating: Customer Lifetime Value (CLV)")
df['CLV'] = df['TotalCharges']  # Direct mapping - TotalCharges represents CLV
print(f"   Mean CLV: ${df['CLV'].mean():.2f}")
print(f"   Median CLV: ${df['CLV'].median():.2f}")
print(f"   Range: ${df['CLV'].min():.2f} to ${df['CLV'].max():.2f}")

feature_dict.append("\n1. CLV (Customer Lifetime Value)")
feature_dict.append("   Definition: Total revenue generated by customer to date")
feature_dict.append("   Calculation: TotalCharges")
feature_dict.append("   Business Use: Identify high-value customers for retention priority")
feature_dict.append(f"   Mean: ${df['CLV'].mean():.2f}")

validation_results.append("\n1. CLV:")
validation_results.append(f"   Non-null count: {df['CLV'].count()} (expected: {len(df)})")
validation_results.append(f"   Negative values: {(df['CLV'] < 0).sum()} (expected: 0)")

# Feature 2: Average Revenue Per User (ARPU)
# Business Definition: Average monthly revenue per customer
# Calculation: MonthlyCharges (direct monthly billing amount)
print("\n📊 Creating: Average Revenue Per User (ARPU)")
df['ARPU'] = df['MonthlyCharges']  # ARPU = monthly charges
print(f"   Mean ARPU: ${df['ARPU'].mean():.2f}/month")
print(f"   Median ARPU: ${df['ARPU'].median():.2f}/month")

feature_dict.append("\n2. ARPU (Average Revenue Per User)")
feature_dict.append("   Definition: Average monthly revenue per customer")
feature_dict.append("   Calculation: MonthlyCharges")
feature_dict.append("   Business Use: Understand customer value tier")
feature_dict.append(f"   Mean: ${df['ARPU'].mean():.2f}/month")

validation_results.append("\n2. ARPU:")
validation_results.append(f"   Non-null count: {df['ARPU'].count()}")
validation_results.append(f"   Zero/negative values: {(df['ARPU'] <= 0).sum()} (expected: 0)")

# Feature 3: Customer Value Segment
# Business Definition: Categorize customers by revenue contribution
# Calculation: Based on ARPU quartiles (Q1=Low, Q2-Q3=Medium, Q4=High)
print("\n📊 Creating: Customer Value Segment")

# Calculate quartiles for ARPU
q1 = df['ARPU'].quantile(0.25)  # 25th percentile
q3 = df['ARPU'].quantile(0.75)  # 75th percentile

# Assign value segment based on ARPU
df['Value_Segment'] = pd.cut(
    df['ARPU'],
    bins=[-np.inf, q1, q3, np.inf],
    labels=['Low Value', 'Medium Value', 'High Value']
)

# Count customers in each segment
value_counts = df['Value_Segment'].value_counts()
print(f"   Low Value: {value_counts.get('Low Value', 0):,} customers")
print(f"   Medium Value: {value_counts.get('Medium Value', 0):,} customers")
print(f"   High Value: {value_counts.get('High Value', 0):,} customers")

feature_dict.append("\n3. Value_Segment")
feature_dict.append("   Definition: Customer revenue tier (Low/Medium/High)")
feature_dict.append("   Calculation: Based on ARPU quartiles")
feature_dict.append("   Business Use: Prioritize high-value customers in retention efforts")

validation_results.append("\n3. Value_Segment:")
validation_results.append(f"   Non-null count: {df['Value_Segment'].count()}")
validation_results.append(f"   Unique values: {df['Value_Segment'].nunique()} (expected: 3)")

print()

# ==================== CATEGORY 2: CHURN RISK INDICATORS ====================
print("-" * 80)
print("CATEGORY 2: CHURN RISK INDICATORS (RULE-BASED)")
print("-" * 80)

feature_dict.append("\n" + "-" * 80)
feature_dict.append("CATEGORY 2: CHURN RISK INDICATORS")
feature_dict.append("-" * 80)

validation_results.append("\n" + "-" * 80)
validation_results.append("CATEGORY 2: CHURN RISK INDICATORS")
validation_results.append("-" * 80)

# Feature 4: High Risk Flag
# Business Rule: Month-to-month contract AND tenure < 12 months
print("\n📊 Creating: High Risk Flag")

df['High_Risk_Flag'] = (
    (df['Contract'] == 'Month-to-month') &
    (df['tenure'] < 12)
).astype(int)

high_risk_count = df['High_Risk_Flag'].sum()
high_risk_churn = df[df['High_Risk_Flag'] == 1]['Churn'].value_counts()
print(f"   High Risk Customers: {high_risk_count:,} ({high_risk_count/len(df)*100:.1f}%)")
if 'Yes' in high_risk_churn.index:
    high_risk_churn_rate = high_risk_churn['Yes'] / high_risk_count * 100
    print(f"   Churn Rate in High Risk: {high_risk_churn_rate:.1f}%")

feature_dict.append("\n4. High_Risk_Flag")
feature_dict.append("   Definition: Customer at high risk of churning")
feature_dict.append("   Rule: Month-to-month contract AND tenure < 12 months")
feature_dict.append("   Business Use: Target for immediate retention intervention")
feature_dict.append(f"   Flagged Customers: {high_risk_count:,}")

validation_results.append("\n4. High_Risk_Flag:")
validation_results.append(f"   Values: {df['High_Risk_Flag'].unique()} (expected: [0, 1])")
validation_results.append(f"   Flagged: {high_risk_count} customers")

# Feature 5: Payment Risk Flag
# Business Rule: Electronic check payment method
print("\n📊 Creating: Payment Risk Flag")

df['Payment_Risk_Flag'] = (
    df['PaymentMethod'] == 'Electronic check'
).astype(int)

payment_risk_count = df['Payment_Risk_Flag'].sum()
print(f"   Payment Risk Customers: {payment_risk_count:,} ({payment_risk_count/len(df)*100:.1f}%)")

feature_dict.append("\n5. Payment_Risk_Flag")
feature_dict.append("   Definition: Customer using high-churn payment method")
feature_dict.append("   Rule: PaymentMethod = 'Electronic check'")
feature_dict.append("   Business Use: Encourage migration to auto-pay methods")
feature_dict.append(f"   Flagged Customers: {payment_risk_count:,}")

validation_results.append("\n5. Payment_Risk_Flag:")
validation_results.append(f"   Values: {df['Payment_Risk_Flag'].unique()} (expected: [0, 1])")
validation_results.append(f"   Flagged: {payment_risk_count} customers")

# Feature 6: Service Risk Flag
# Business Rule: No tech support AND no online security
print("\n📊 Creating: Service Risk Flag")

df['Service_Risk_Flag'] = (
    (df['TechSupport'] == 'No') &
    (df['OnlineSecurity'] == 'No')
).astype(int)

service_risk_count = df['Service_Risk_Flag'].sum()
print(f"   Service Risk Customers: {service_risk_count:,} ({service_risk_count/len(df)*100:.1f}%)")

feature_dict.append("\n6. Service_Risk_Flag")
feature_dict.append("   Definition: Customer with minimal service adoption")
feature_dict.append("   Rule: No TechSupport AND No OnlineSecurity")
feature_dict.append("   Business Use: Target for service upsell campaigns")
feature_dict.append(f"   Flagged Customers: {service_risk_count:,}")

validation_results.append("\n6. Service_Risk_Flag:")
validation_results.append(f"   Values: {df['Service_Risk_Flag'].unique()} (expected: [0, 1])")
validation_results.append(f"   Flagged: {service_risk_count} customers")

# Feature 7: Overall Risk Score
# Business Definition: Composite risk score (0-3)
print("\n📊 Creating: Overall Risk Score")

df['Risk_Score'] = (
    df['High_Risk_Flag'] +
    df['Payment_Risk_Flag'] +
    df['Service_Risk_Flag']
)

# Count customers by risk score
risk_distribution = df['Risk_Score'].value_counts().sort_index()
print("   Risk Score Distribution:")
for score, count in risk_distribution.items():
    print(f"     Score {score}: {count:,} customers ({count/len(df)*100:.1f}%)")

feature_dict.append("\n7. Risk_Score")
feature_dict.append("   Definition: Composite churn risk indicator (0-3)")
feature_dict.append("   Calculation: Sum of High_Risk + Payment_Risk + Service_Risk flags")
feature_dict.append("   Business Use: Prioritize retention resources (higher score = higher priority)")

validation_results.append("\n7. Risk_Score:")
validation_results.append(f"   Range: {df['Risk_Score'].min()} to {df['Risk_Score'].max()} (expected: 0-3)")
validation_results.append(f"   Mean: {df['Risk_Score'].mean():.2f}")

print()

# ==================== CATEGORY 3: SERVICE ADOPTION METRICS ====================
print("-" * 80)
print("CATEGORY 3: SERVICE ADOPTION METRICS")
print("-" * 80)

feature_dict.append("\n" + "-" * 80)
feature_dict.append("CATEGORY 3: SERVICE ADOPTION METRICS")
feature_dict.append("-" * 80)

validation_results.append("\n" + "-" * 80)
validation_results.append("CATEGORY 3: SERVICE ADOPTION METRICS")
validation_results.append("-" * 80)

# Feature 8: Total Services Count
# Business Definition: Number of services customer subscribes to
print("\n📊 Creating: Total Services Count")

# Define service columns
service_columns = ['PhoneService', 'InternetService', 'OnlineSecurity', 
                   'OnlineBackup', 'DeviceProtection', 'TechSupport', 
                   'StreamingTV', 'StreamingMovies']

# Count "Yes" values across service columns
df['Total_Services'] = 0
for col in service_columns:
    if col == 'InternetService':
        # InternetService has "DSL", "Fiber optic", "No"
        df['Total_Services'] += (df[col] != 'No').astype(int)
    elif col == 'PhoneService':
        # PhoneService has "Yes", "No"
        df['Total_Services'] += (df[col] == 'Yes').astype(int)
    else:
        # Other services have "Yes", "No", "No internet service"
        df['Total_Services'] += (df[col] == 'Yes').astype(int)

print(f"   Mean services per customer: {df['Total_Services'].mean():.2f}")
print(f"   Range: {df['Total_Services'].min()} to {df['Total_Services'].max()} services")

service_dist = df['Total_Services'].value_counts().sort_index()
print("   Distribution:")
for count, customers in service_dist.items():
    print(f"     {count} services: {customers:,} customers")

feature_dict.append("\n8. Total_Services")
feature_dict.append("   Definition: Number of services customer subscribes to")
feature_dict.append("   Calculation: Count of active service subscriptions")
feature_dict.append("   Business Use: Identify service adoption levels")
feature_dict.append(f"   Mean: {df['Total_Services'].mean():.2f} services")

validation_results.append("\n8. Total_Services:")
validation_results.append(f"   Range: {df['Total_Services'].min()} to {df['Total_Services'].max()}")
validation_results.append(f"   Mean: {df['Total_Services'].mean():.2f}")

# Feature 9: Service Adoption Rate
# Business Definition: Percentage of available services customer uses
print("\n📊 Creating: Service Adoption Rate")

max_services = len(service_columns)
df['Service_Adoption_Rate'] = (df['Total_Services'] / max_services * 100).round(2)

print(f"   Mean adoption rate: {df['Service_Adoption_Rate'].mean():.1f}%")
print(f"   Customers with <25% adoption: {(df['Service_Adoption_Rate'] < 25).sum():,}")
print(f"   Customers with >75% adoption: {(df['Service_Adoption_Rate'] > 75).sum():,}")

feature_dict.append("\n9. Service_Adoption_Rate")
feature_dict.append("   Definition: Percentage of available services in use")
feature_dict.append("   Calculation: (Total_Services / 8) * 100")
feature_dict.append("   Business Use: Identify upsell opportunities")
feature_dict.append(f"   Mean: {df['Service_Adoption_Rate'].mean():.1f}%")

validation_results.append("\n9. Service_Adoption_Rate:")
validation_results.append(f"   Range: {df['Service_Adoption_Rate'].min()}% to {df['Service_Adoption_Rate'].max()}%")
validation_results.append(f"   Mean: {df['Service_Adoption_Rate'].mean():.2f}%")

print()

# ==================== CATEGORY 4: CUSTOMER LIFECYCLE STAGE ====================
print("-" * 80)
print("CATEGORY 4: CUSTOMER LIFECYCLE STAGE")
print("-" * 80)

feature_dict.append("\n" + "-" * 80)
feature_dict.append("CATEGORY 4: CUSTOMER LIFECYCLE STAGE")
feature_dict.append("-" * 80)

validation_results.append("\n" + "-" * 80)
validation_results.append("CATEGORY 4: CUSTOMER LIFECYCLE STAGE")
validation_results.append("-" * 80)

# Feature 10: Tenure Segment
# Business Definition: Customer lifecycle stage based on tenure
print("\n📊 Creating: Tenure Segment")

df['Tenure_Segment'] = pd.cut(
    df['tenure'],
    bins=[0, 12, 24, 48, 72],
    labels=['New (0-12m)', 'Growing (13-24m)', 'Mature (25-48m)', 'Loyal (49-72m)'],
    include_lowest=True
)

tenure_dist = df['Tenure_Segment'].value_counts()
print("   Customer Lifecycle Distribution:")
for segment, count in tenure_dist.items():
    print(f"     {segment}: {count:,} customers ({count/len(df)*100:.1f}%)")

feature_dict.append("\n10. Tenure_Segment")
feature_dict.append("   Definition: Customer lifecycle stage")
feature_dict.append("   Categories: New (0-12m), Growing (13-24m), Mature (25-48m), Loyal (49-72m)")
feature_dict.append("   Business Use: Tailor retention strategies by lifecycle stage")

validation_results.append("\n10. Tenure_Segment:")
validation_results.append(f"   Unique values: {df['Tenure_Segment'].nunique()} (expected: 4)")
validation_results.append(f"   Non-null count: {df['Tenure_Segment'].count()}")

# Feature 11: Contract Stability Score
# Business Definition: Numeric score for contract commitment level
print("\n📊 Creating: Contract Stability Score")

contract_scores = {
    'Month-to-month': 1,
    'One year': 2,
    'Two year': 3
}
df['Contract_Stability_Score'] = df['Contract'].map(contract_scores)

print(f"   Mean stability score: {df['Contract_Stability_Score'].mean():.2f}")
stability_dist = df['Contract_Stability_Score'].value_counts().sort_index()
for score, count in stability_dist.items():
    contract_type = [k for k, v in contract_scores.items() if v == score][0]
    print(f"     Score {score} ({contract_type}): {count:,} customers")

feature_dict.append("\n11. Contract_Stability_Score")
feature_dict.append("   Definition: Numeric indicator of contract commitment")
feature_dict.append("   Scale: 1 (Month-to-month), 2 (One year), 3 (Two year)")
feature_dict.append("   Business Use: Quantify contract stability for analysis")

validation_results.append("\n11. Contract_Stability_Score:")
validation_results.append(f"   Range: {df['Contract_Stability_Score'].min()} to {df['Contract_Stability_Score'].max()} (expected: 1-3)")
validation_results.append(f"   Non-null count: {df['Contract_Stability_Score'].count()}")

print()

# ==================== CATEGORY 5: BEHAVIORAL FEATURES ====================
print("-" * 80)
print("CATEGORY 5: BEHAVIORAL FEATURES")
print("-" * 80)

feature_dict.append("\n" + "-" * 80)
feature_dict.append("CATEGORY 5: BEHAVIORAL FEATURES")
feature_dict.append("-" * 80)

validation_results.append("\n" + "-" * 80)
validation_results.append("CATEGORY 5: BEHAVIORAL FEATURES")
validation_results.append("-" * 80)

# Feature 12: Payment Reliability Score
# Business Definition: Score based on paperless billing and auto-pay usage
print("\n📊 Creating: Payment Reliability Score")

df['Payment_Reliability_Score'] = 0

# Add points for paperless billing
df.loc[df['PaperlessBilling'] == 'Yes', 'Payment_Reliability_Score'] += 1

# Add points for automatic payment methods
auto_pay_methods = ['Credit card (automatic)', 'Bank transfer (automatic)']
df.loc[df['PaymentMethod'].isin(auto_pay_methods), 'Payment_Reliability_Score'] += 2

reliability_dist = df['Payment_Reliability_Score'].value_counts().sort_index()
print("   Payment Reliability Distribution:")
for score, count in reliability_dist.items():
    print(f"     Score {score}: {count:,} customers ({count/len(df)*100:.1f}%)")

feature_dict.append("\n12. Payment_Reliability_Score")
feature_dict.append("   Definition: Indicator of payment automation level")
feature_dict.append("   Calculation: +1 for paperless, +2 for auto-pay (0-3 scale)")
feature_dict.append("   Business Use: Identify customers needing payment support")

validation_results.append("\n12. Payment_Reliability_Score:")
validation_results.append(f"   Range: {df['Payment_Reliability_Score'].min()} to {df['Payment_Reliability_Score'].max()} (expected: 0-3)")
validation_results.append(f"   Mean: {df['Payment_Reliability_Score'].mean():.2f}")

# Feature 13: Has_Dependents_or_Partner
# Business Definition: Customer has family (dependents or partner)
print("\n📊 Creating: Has Family Flag")

df['Has_Family'] = (
    (df['Partner'] == 'Yes') | (df['Dependents'] == 'Yes')
).astype(int)

family_count = df['Has_Family'].sum()
print(f"   Customers with family: {family_count:,} ({family_count/len(df)*100:.1f}%)")

feature_dict.append("\n13. Has_Family")
feature_dict.append("   Definition: Customer has partner or dependents")
feature_dict.append("   Rule: Partner = Yes OR Dependents = Yes")
feature_dict.append("   Business Use: Family plans and bundle offers")

validation_results.append("\n13. Has_Family:")
validation_results.append(f"   Values: {df['Has_Family'].unique()} (expected: [0, 1])")
validation_results.append(f"   Customers with family: {family_count}")

# Feature 14: Senior Customer Flag
# Business Definition: Customer is senior citizen
print("\n📊 Creating: Is Senior Flag")

# SeniorCitizen is already 0/1, just rename for clarity
df['Is_Senior'] = df['SeniorCitizen']

senior_count = df['Is_Senior'].sum()
print(f"   Senior customers: {senior_count:,} ({senior_count/len(df)*100:.1f}%)")

feature_dict.append("\n14. Is_Senior")
feature_dict.append("   Definition: Customer is senior citizen (65+)")
feature_dict.append("   Source: SeniorCitizen column")
feature_dict.append("   Business Use: Age-based retention strategies")

validation_results.append("\n14. Is_Senior:")
validation_results.append(f"   Values: {df['Is_Senior'].unique()} (expected: [0, 1])")
validation_results.append(f"   Senior customers: {senior_count}")

print()

# ==================== CATEGORY 6: ENGAGEMENT METRICS ====================
print("-" * 80)
print("CATEGORY 6: ENGAGEMENT METRICS")
print("-" * 80)

feature_dict.append("\n" + "-" * 80)
feature_dict.append("CATEGORY 6: ENGAGEMENT METRICS")
feature_dict.append("-" * 80)

validation_results.append("\n" + "-" * 80)
validation_results.append("CATEGORY 6: ENGAGEMENT METRICS")
validation_results.append("-" * 80)

# Feature 15: Engagement Level
# Business Definition: Overall customer engagement (Low/Medium/High)
print("\n📊 Creating: Engagement Level")

# Calculate engagement score based on multiple factors
engagement_score = 0

# Factor 1: Service adoption (0-3 points)
df['_temp_service_points'] = pd.cut(
    df['Service_Adoption_Rate'],
    bins=[0, 25, 50, 100],
    labels=[1, 2, 3],
    include_lowest=True
).astype(float)
engagement_score += df['_temp_service_points']

# Factor 2: Contract commitment (1-3 points)
engagement_score += df['Contract_Stability_Score']

# Factor 3: Payment reliability (0-3 points)
engagement_score += df['Payment_Reliability_Score']

# Factor 4: Tenure longevity
df['_temp_tenure_points'] = pd.cut(
    df['tenure'],
    bins=[0, 12, 36, 72],
    labels=[1, 2, 3],
    include_lowest=True
).astype(float)
engagement_score += df['_temp_tenure_points']

# Total score: 3-12, categorize into Low/Medium/High
df['Engagement_Level'] = pd.cut(
    engagement_score,
    bins=[0, 6, 9, 13],
    labels=['Low Engagement', 'Medium Engagement', 'High Engagement'],
    include_lowest=True
)

engagement_dist = df['Engagement_Level'].value_counts()
print("   Engagement Distribution:")
for level, count in engagement_dist.items():
    print(f"     {level}: {count:,} customers ({count/len(df)*100:.1f}%)")

# Clean up temporary columns
df.drop(['_temp_service_points', '_temp_tenure_points'], axis=1, inplace=True)

feature_dict.append("\n15. Engagement_Level")
feature_dict.append("   Definition: Overall customer engagement level")
feature_dict.append("   Calculation: Composite of services, contract, payment, tenure")
feature_dict.append("   Categories: Low, Medium, High")
feature_dict.append("   Business Use: Identify disengaged customers for re-engagement campaigns")

validation_results.append("\n15. Engagement_Level:")
validation_results.append(f"   Unique values: {df['Engagement_Level'].nunique()} (expected: 3)")
validation_results.append(f"   Non-null count: {df['Engagement_Level'].count()}")

# Feature 16: Revenue per Tenure Month
# Business Definition: Average monthly revenue contribution
print("\n📊 Creating: Revenue per Tenure Month")

# Avoid division by zero
df['Revenue_per_Month'] = df['TotalCharges'] / df['tenure'].replace(0, 1)

print(f"   Mean revenue per month: ${df['Revenue_per_Month'].mean():.2f}")
print(f"   Median revenue per month: ${df['Revenue_per_Month'].median():.2f}")

feature_dict.append("\n16. Revenue_per_Month")
feature_dict.append("   Definition: Average monthly revenue per tenure month")
feature_dict.append("   Calculation: TotalCharges / tenure")
feature_dict.append("   Business Use: Identify consistent revenue contributors")

validation_results.append("\n16. Revenue_per_Month:")
validation_results.append(f"   Mean: ${df['Revenue_per_Month'].mean():.2f}")
validation_results.append(f"   Non-null count: {df['Revenue_per_Month'].count()}")

print()

# ==================== SAVE ENRICHED DATASET ====================
print("-" * 80)
print("SAVING ENRICHED DATASET")
print("-" * 80)

print(f"\n💾 Saving enriched dataset to: {output_path}")
df.to_csv(output_path, index=False)
print(f"✅ Enriched dataset saved")
print(f"   Final shape: {df.shape[0]} rows × {df.shape[1]} columns")
print(f"   New features added: {df.shape[1] - 33}")  # Original had 33 columns

# ==================== SAVE FEATURE DICTIONARY ====================
print(f"\n📖 Saving feature dictionary to: {dictionary_path}")

feature_dict.append("\n" + "=" * 80)
feature_dict.append("SUMMARY")
feature_dict.append("=" * 80)
feature_dict.append(f"\nTotal Features Created: 16")
feature_dict.append(f"Original Columns: 33")
feature_dict.append(f"Final Columns: {df.shape[1]}")
feature_dict.append("")
feature_dict.append("Categories:")
feature_dict.append("  1. Customer Value Metrics (3 features)")
feature_dict.append("  2. Churn Risk Indicators (4 features)")
feature_dict.append("  3. Service Adoption Metrics (2 features)")
feature_dict.append("  4. Customer Lifecycle Stage (2 features)")
feature_dict.append("  5. Behavioral Features (3 features)")
feature_dict.append("  6. Engagement Metrics (2 features)")

with open(dictionary_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(feature_dict))
print(f"✅ Feature dictionary saved")

# ==================== SAVE VALIDATION REPORT ====================
print(f"\n✅ Saving validation report to: {validation_path}")

validation_results.append("\n" + "=" * 80)
validation_results.append("VALIDATION SUMMARY")
validation_results.append("=" * 80)
validation_results.append("\n✅ All features created successfully")
validation_results.append(f"✅ No missing values in engineered features")
validation_results.append(f"✅ All numeric features within expected ranges")
validation_results.append(f"✅ All categorical features have expected values")
validation_results.append("")
validation_results.append("Dataset ready for Stage 7 (Analytical Reasoning)")

with open(validation_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(validation_results))
print(f"✅ Validation report saved")

# ==================== FINAL SUMMARY ====================
print("\n" + "=" * 80)
print("✅ FEATURE ENGINEERING COMPLETE")
print("=" * 80)
print()
print("Outputs Generated:")
print(f"  📊 Enriched Dataset: {output_path}")
print(f"     - {df.shape[0]:,} rows × {df.shape[1]} columns")
print(f"     - {df.shape[1] - 33} new features added")
print()
print(f"  📖 Feature Dictionary: {dictionary_path}")
print(f"     - Definitions and business use cases for all features")
print()
print(f"  ✅ Validation Report: {validation_path}")
print(f"     - Quality checks for all engineered features")
print()
print("New Features Created (16 total):")
print("  • Customer Value: CLV, ARPU, Value_Segment")
print("  • Risk Indicators: High_Risk_Flag, Payment_Risk_Flag, Service_Risk_Flag, Risk_Score")
print("  • Service Metrics: Total_Services, Service_Adoption_Rate")
print("  • Lifecycle: Tenure_Segment, Contract_Stability_Score")
print("  • Behavioral: Payment_Reliability_Score, Has_Family, Is_Senior")
print("  • Engagement: Engagement_Level, Revenue_per_Month")
print()
print("Key Business Metrics Available:")
high_risk_pct = (df['High_Risk_Flag'].sum() / len(df) * 100)
high_value_pct = (df['Value_Segment'] == 'High Value').sum() / len(df) * 100
low_engagement_pct = (df['Engagement_Level'] == 'Low Engagement').sum() / len(df) * 100

print(f"  • High-Risk Customers: {df['High_Risk_Flag'].sum():,} ({high_risk_pct:.1f}%)")
print(f"  • High-Value Customers: {(df['Value_Segment'] == 'High Value').sum():,} ({high_value_pct:.1f}%)")
print(f"  • Low Engagement: {(df['Engagement_Level'] == 'Low Engagement').sum():,} ({low_engagement_pct:.1f}%)")
print(f"  • Mean Risk Score: {df['Risk_Score'].mean():.2f}/3")
print(f"  • Mean Service Adoption: {df['Service_Adoption_Rate'].mean():.1f}%")
print()
print("Next Step: Proceed to Stage 7 (Analytical Reasoning)")
print("=" * 80)
